name: workshop-techart
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - autopep8
  - certifi==2020.12.5
  - numpy
  - opencv==4.5.1
  - pyqt
  - pycodestyle
  - six
  - toml
  - pip
  - pip:
    - mkl-fft
    - mkl-random==1.1.1
    - mkl-service==2.3.0